downgrade @sap/hdi-deploy due to bug in 4.9.0 (#278)
@hdi-deployer in version 4.9.0 has an issue:

Error: Cannot find module 'core-util-is'

Version 4.8.2 is fine. Hence, we temporarily downgrade