Update cds-services to 3.7.1 (#435)
To fix this issue, we need to maintain a newer version of Apache
commons-io:

```
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/io/input/UnsynchronizedBufferedReader
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
```

Liquibase brings an old version of commons-io:

```
[INFO] +- org.liquibase:liquibase-core:jar:4.29.2:runtime
[INFO] |  +- com.opencsv:opencsv:jar:5.9:runtime
[INFO] |  +- javax.xml.bind:jaxb-api:jar:2.3.1:runtime
[INFO] |  +- commons-io:commons-io:jar:2.16.1:runtime
[INFO] |  +- org.apache.commons:commons-collections4:jar:4.4:runtime
[INFO] |  +- org.apache.commons:commons-text:jar:1.12.0:runtime
[INFO] |  \- org.apache.commons:commons-lang3:jar:3.17.0:compile
```